# Generated by Django 5.2.15 on 2026-06-26 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                default=1234567899,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="National code must contain exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +98912xxxxxxx",
                        regex="^\\+989\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters are allowed.", regex="^[A-Za-zآ-ی ]+$"
                    )
                ],
            ),
        ),
    ]
