# Generated by Django 5.2.15 on 2026-06-28 18:05

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_national_code_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[accounts.validators.validate_national_code],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +989xxxxxxxxx",
                        regex="^\\+989\\d{9}$",
                    )
                ],
            ),
        ),
    ]
