# Generated by Django 5.2.15 on 2026-06-28 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_national_code_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters are allowed.", regex="^[A-Za-zآ-ی ]+$"
                    ),
                    django.core.validators.MinLengthValidator(4),
                ],
            ),
        ),
    ]
