# Generated by Django 5.2.15 on 2026-06-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "Customer"), (2, "Admin"), (3, "Superuser")], default=1
            ),
        ),
    ]
