# Generated by Django 5.2.15 on 2026-06-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
