# Generated by Django 5.2.15 on 2026-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_orderitem_tax_amount_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="address_name",
            field=models.CharField(default="Address", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
